import { v4 as uuidv4 } from 'uuid'
import { NewCreatedDocType } from '@/modules/cms/domain/DocType'
import plopClient from '../utils/plop/plopClient'
import generators from '../utils/plop/generators'
import eslintUtils from '../utils/eslint'
import gitUtils from '../utils/git'

async function createDocType(docType: NewCreatedDocType) : Promise<void> {
  await plopClient.getGenerator(generators.createDocTypeSchema).runActions({
    fileName : docType.info.singularName,
    doctype  : {
      referenceId: `doctype:${uuidv4()}`,
      ...docType,
    },
  })

  eslintUtils.formatAutoGeneratedFiles()
  gitUtils.addAutoGeneratedFilesToStage()
}

export default createDocType
