export enum ApiErrorCodes {
  // Generic
  UNCONTROLLED_ERROR = 'UNCONTROLLED_ERROR',
  INVALID_REQUEST_SCHEMA = 'INVALID_REQUEST_SCHEMA',
  UNAUTHORIZED = 'UNAUTHORIZED',

  // Tenants
  TENANT_ALREADY_EXISTS = 'TENANT_ALREADY_EXISTS',
}

export default ApiErrorCodes
