import { exec } from 'child_process'
import path from 'path'
import config from '../../config/config'

export function formatAutoGeneratedFiles() {
  exec(`eslint --fix ${path.join(config.output, '/**/*.ts')}`)
}

export default formatAutoGeneratedFiles
