import { exec } from 'child_process'
import path from 'path'
import config from '../../config/config'

export function addAutoGeneratedFilesToStage() {
  exec(`git add ${path.join(config.output, '/**/*')}`)
}

export default addAutoGeneratedFilesToStage
